---
version: '2.4'

services:

  dvwa_web:
    #Built with as base cytopia/dvwa
    image: adrianaues/dvwa-esagent:apm
    restart: unless-stopped
    hostname: dvwa_app
    volumes:
      - ea_state:/usr/share/elastic-agent/state/:z
      ## comment both /sys lines for non linux kernel
      ## E.g. Mac
      - /sys/kernel/debug:/sys/kernel/debug:ro,z
      - /sys/fs/bpf:/sys/fs/bpf:ro,z
    ports:
      - "${LISTEN_PORT:-3000}:80"
    cap_add:
      - ALL
    networks:
      - dvwa-net
    environment:
      - RECAPTCHA_PRIV_KEY=${RECAPTCHA_PRIV_KEY:-}
      - RECAPTCHA_PUB_KEY=${RECAPTCHA_PUB_KEY:-}
      - SECURITY_LEVEL=${SECURITY_LEVEL:-medium}
      - PHPIDS_ENABLED=${PHPIDS_ENABLED:-0}
      - PHPIDS_VERBOSE=${PHPIDS_VERBOSE:-0}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS:-0}
      - MYSQL_HOSTNAME=dvwa_db
      - MYSQL_DATABASE=dvwa
      - MYSQL_USERNAME=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
      - FLEET_ENROLL=1
      - FLEET_ENROLLMENT_TOKEN=
      - FLEET_URL=
      - ELASTIC_APM_SECRET_TOKEN=
      - ELASTIC_APM_SERVER_URL=
      - ELASTIC_ENDPOINT_K8S=true
      - ELASTIC_APM_SERVICE_NAME=DVWA
      # Don't capture Error due to PHP Agent Bug
      # https://github.com/elastic/apm-agent-php/issues/1022
      - ELASTIC_APM_CAPTURE_ERRORS=false

  dvwa_db:
    image: mariadb:10.7
    hostname: dvwa_db
    volumes:
      - dvwa_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
    restart: unless-stopped
    networks:
      - dvwa-net

networks:
  dvwa-net:
            #driver: bridge

volumes:
  dvwa_db_data:
  ea_state:
